server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/linebotdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: linebot
    password: LinePass!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

line:
  channelSecret: ${LINE_CHANNEL_SECRET}
  channelAccessToken: ${LINE_CHANNEL_ACCESS_TOKEN}
